services:
  interview-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: interview-app

    ports:
      - "8501:8501"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

    restart: unless-stopped